### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by TeachReo** [openfun/bbb-stress-test#3]
Hello 
thanks for your script.
I need to do stress test on bbb-server 2.2.28 and I have this error when I start the script :
```
info:    Doris2946 join the conference
debug:   waiting for audio prompt ([aria-label="Microphone"])
debug:   click on Microphone
error:   Unable to initialize client Doris2946 : TimeoutError: waiting for selector ".ReactModal__Overlay" to be hidden failed: timeout 30000ms exceeded
```
Do you know how I can solve it ?
Regards
Fabrice

**Comment by madmatah** [comment]
Hello @TeachReo,

Thanks for you interrest in our project.
I haven't any BBB 2.2.28 server to reproduce your problem, but it seems that the interface displayed when connecting to the BBB meeting does not contains the «Microphone» option.

Can you please check the following :
- The conference is already running when you start the script ?
- Connect to your meeting in your browser, as a moderator, do you see the  "Microphone" option in the audio selection dialog ?
- Can you execute the script without errors in you set `BBB_CLIENTS_MIC=0` and `BBB_CLIENTS_LISTEN_ONLY=1` ?

**Comment by TeachReo** [comment]
The conference is already running when you start the script ?  
- yes
Connect to your meeting in your browser, as a moderator, do you see the "Microphone" option in the audio selection dialog ?
- yes I see it, I edited the code to for watch if Microphone is present, the answer is true
Can you execute the script without errors in you set BBB_CLIENTS_MIC=0 and BBB_CLIENTS_LISTEN_ONLY=1 ?
- it works perfectly with listen_only
![Capture d’écran de 2020-11-02 15-53-20](https://user-images.githubusercontent.com/4716847/97882226-a8eb8400-1d23-11eb-848e-843b8edaf858.png)

**Comment by madmatah** [comment]
Ok, thanks for your feedback.
Sorry I made a mistake in my previous comment : according to the debug logs, the dialog with the microphone is displayed, but it does not disapear when the button is clicked.

I see 2 options to understand better what's going on :

1) You can inspect the pupeteer console messages, by adding the following code [here](https://github.com/openfun/bbb-stress-test/blob/master/lib/stress-test.js#L13) : 
```javascript
  page
    .on('console', message =>
      logger.log(`${message.type().substr(0, 3).toUpperCase()} ${message.text()}`))
    .on('pageerror', ({ message }) => logger.log(message))
    .on('response', response =>
      logger.log(`${response.status()} ${response.url()}`))
    .on('requestfailed', request =>
      logger.log(`${request.failure().errorText} ${request.url()}`))
```

2) You can take a screenshot of the page after the button is clicked with the following code [here](https://github.com/openfun/bbb-stress-test/blob/master/lib/stress-test.js#L20) : 
  ```javascript
     await page.pdf({ path: "/tmp/screenshot.pdf" });
  ```
   (The screenshot will be stored in the docker container)
   It will allow you to see what's happening.


That's all I can suggest for the moment.
I'll investigate on this issue later, can't do it now.

**Comment by madmatah** [comment]
Hello @TeachReo, thanks again for your issue.
The initial script was tested on a BBB instance with echo test, that's why it did not work on your instance (and most BBB instances actually). It has been fixed.
