### ISSUE TITLE
make list-meetings fails

### ISSUE THREAD

**Issue by bpetit** [openfun/bbb-stress-test#4]
Hi,

Running `make list-meetings` fails because of a missing js dependency:

```
WARNING: Image for service app was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
🐳(entrypoint) creating user running in the container...
🐳(entrypoint) running your command: ./cli.js list-meetings
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'lodash/fp'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/app/lib/command-helpers.js:1:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
make: *** [Makefile:51 : list-meetings] Erreur 1
```
Any idea of what could cause that ?

I run on Ubuntu 20.04.1 and Docker version 19.03.8, build afacb8b7f0 but I imagine it's not relevant as it seems related to be about what dependencies are installed or not in the container.

Thanks

**Comment by madmatah** [comment]
Hello @bpetit,

Sadly, I did not manage to reproduce your problem and I'm using the exact same environment as you, with an empty docker cache. Can you please give me more details about what you did exactly before the `make list-meetings` ?
When you wrote your issue, there was a problem with the `make bootstrap` command. And as a result, the instructions given in the Getting started section of the README were impossible to follow as described. It is now fixed.

 Can you provide the logs of the `make build` command ? The lodash dependency is pinned in the `package.json` and in the `yarn.lock` files provided with the project.  I don't see why this dependency is missing in your case.

**Comment by bpetit** [comment]
Hi,

Thanks for your answer. I pulled once again and ran both `make bootstrap` and `make build` successfully.
Now I get this completely different error running `make list-meetings`:

```
🐳(entrypoint) creating user running in the container...
🐳(entrypoint) running your command: ./cli.js list-meetings
error:   Request failed with status code 404
```
So I assume it has something to do with my configuration values or something.

This particular issue seems fixed for me.

Thanks a lot !
